### ISSUE TITLE
Yarn 2 PnP Compatibility

### ISSUE THREAD

**Issue by bohushvitali** [johnsoncodehk/vue-tsc#5]
Available workarounds for adding Yarn 2 PnP compatibility seams like doesn't work in workspace created using [yarn.build](https://yarn.build/). Will be nice to find alternative to extraction of `volar.vsix` in `vue-tsc`

```
➤ YN0000: ┌ Run build for packages/volar-starter
➤ YN0009: │ ┌ [stderr] packages/volar-starter
➤ YN0009: │ │ events.js:292
➤ YN0009: │ │       throw er; // Unhandled 'error' event
➤ YN0009: │ │       ^
➤ YN0009: │ │ Error: EROFS: read-only filesystem, mkdir '/node_modules/vue-tsc/volar'
```

running `yarn unplug vue-tsc` in `packages/volar-starter` resulting in:
```
➤ YN0009: │ │ Error: vue-tsc tried to access vscode-languageserver, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
➤ YN0009: │ │ Required package: vscode-languageserver (via "vscode-languageserver/node")
➤ YN0009: │ │ Required by: vue-tsc@npm:0.0.14
```

adding to .yarnrc.yml
```yaml
packageExtensions:
  "vue-tsc@*":
    dependencies:
      "vscode-languageserver": "*"
      "vscode-css-languageservice": "*"
      "vscode-html-languageservice": "*"
      "@vue/shared": "*"
```

resulting in:

```
➤ YN0009: │ │ Error: vue-tsc tried to access @volar/vscode-pug-languageservice, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
➤ YN0009: │ │ Required package: @volar/vscode-pug-languageservice (via "@volar/vscode-pug-languageservice")
➤ YN0009: │ │ Required by: vue-tsc@npm:0.0.14
```

`@volar/vscode-pug-languageservice` isn't published on npm and Yarn cannot resolve it from `.yarn/unplugged/vue-tsc-npm-0.0.14-*/node_modules/vue-tsc/volar/extension/node_modules`
